name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Install goose
        runs: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Build
        run: ./scripts/buildprod.sh

      - name: Auth Gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Build Docker Image and Push to Google Artifact Registry
        run: gcloud builds submit --substitutions=_VERSION=0.1.0

      - name: Run Migrations
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image asia-south2-docker.pkg.dev/notely-448017/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-448017 --max-instances=4
